name: Process Video  # 工作流程的名称

on:
  workflow_dispatch:  # 手动触发工作流程

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout repository  # 签出仓库代码
        uses: actions/checkout@v2
        
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: setup ffmpeg  # 安装 ffmpeg
        run: |
          sudo apt update  # 更新软件包列表
          sudo apt install -y ffmpeg  # 安装 ffmpeg
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download file from S3
        run: |
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/input.mp4 ./input.mp4

      - name: Run Go
        run: go run main.go

      - name: Upload file to S3
        run: |
          aws s3 cp ./output.mp4 s3://${{ secrets.S3_BUCKET_NAME }}/output.mp4
