name: video2audio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Download file
        run: |
          wget -O input_video.mkv https://github.com/334456777/ffcut/releases/download/1.1.1/video.mkv 

      - name: Check if input file exists
        run: |
          if [ ! -f "input_video.mkv" ]; then echo "Input file not found"; exit 1; fi

      - name: Run video processing script
        run: |
          ffmpeg -i input_video.mkv -vn -acodec libmp3lame -q:a 2 output_audio.mp3

      - name: Check if output file exists
        run: |
          if [ ! -f "output_audio.mp3" ]; then echo "Output file not found"; exit 1; fi

      - name: Upload file to S3
        run: |
          aws s3 cp ./output_audio.mp3 s3://${{ secrets.S3_BUCKET_NAME }}/audio.mp3
