name: yml

on:
  schedule:
    - cron: '40 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: download file
        run: |
          wget -q --timeout=30 -O ${{ secrets.NAME }} ${{ secrets.URL }}
          wget -q --timeout=30 -O ${{ secrets.ONE_NAME }} ${{ secrets.ONE_URL }}
          wget -q --timeout=30 -O ${{ secrets.TWO_NAME }} ${{ secrets.TWO_URL }}
          wget -q --timeout=30 -O ${{ secrets.THR_NAME }} ${{ secrets.THR_URL }}


      - name: Upload file to S3
        run: |
          aws s3 cp ${{ secrets.NAME }} ${{ secrets.AWS_S3_NAME }} --quiet
          aws s3 cp ${{ secrets.ONE_NAME }} ${{ secrets.AWS_S3_NAME }} --quiet
          aws s3 cp ${{ secrets.TWO_NAME }} ${{ secrets.AWS_S3_NAME }} --quiet
          aws s3 cp ${{ secrets.THR_NAME }} ${{ secrets.AWS_S3_NAME }} --quiet
